import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import * as Items from './items'


export default function Documentation() {

    return (
        <div className="w-full h-full">
            <Head>
                <title>API Docs</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex flex-col items-center justify-start w-full h-full">
                <h1 className="text-lg font-bold p-10">
                    API Docs
                </h1>
                <div className="flex flex-row items-start justify-start w-full h-full p-4 border-r border-gray-200 dark:border-gray-700">
                    <div className="flex flex-col items-start justify-start w-1/5 h-full p-4 border-r border-gray-200 dark:border-gray-700 sticky top-0">
                        <div className="flex flex-col items-start justify-start w-full">
                            <h2 className="text-lg font-bold">API v1.0</h2>
                            <ul className='pl-4'>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#addGame'>Add Game</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#getBets'>Get Available Bets</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#getAvailableDays'>Get Available Days</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#generate'>Generate Ticket</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#getTicket'>Get Ticket</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#winners'>Get Winners</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#getUserTickets'>Get User tickets</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#addReview'>Add Review</a></li>
                                <li className="text-gray-500 dark:text-gray-400"><a href='#getReviews'>Get Reviews</a></li>
                            </ul>
                        </div>
                    </div>

                    <div className="flex flex-col items-center justify-center w-full p-4 overflow-x-hidden">

                        {Object.values(Items).map((Item, index) => (
                            <Item key={index} />
                        ))}



                    </div>
                </div>
            </main>
        </div>
    )
}