import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Documentation from '@/components/Documentation'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [unlock, setUnlock] = useState(false)

  useEffect(() => {
    //check if session is in local storage
    let lastLogin: string = localStorage.getItem("lastLogin") || ""
    if (lastLogin) {
      //check if session is valid
      let now = new Date().getTime()
      let diff = now - new Number(lastLogin).valueOf()
      if (diff < 1000 * 60 * 60 * 24) {
        setUnlock(true)
      }
    }
  }, [setUnlock])

  const checkPasword = (event: string) => {
    if (event == "steaua") {
      //add session to local storage
      localStorage.setItem("lastLogin", new Date().getTime().toString())
      setUnlock(true)
    }
  }

  if (unlock) {
    return <Documentation />
  }
  else {
    return (
      <div className={styles.container}>
        <Head>
          <title>LA Castigam Impreuna</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <input
            id="outlined-password-input"
            type="password"
            autoComplete="current-password"
            onChange={(event) => checkPasword(event.target.value)}
          />
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}
